### PR TITLE
Added support for github actions for checking CLA.

### PR DESCRIPTION
**Pull request by kiivihal**
This version uses the CLA action provided by SAP, see https://github.com/cla-assistant/github-action.

The benefit of this workflow is that it adds the signatures to the repository. This is then also a list of external contributors.

### CODE REVIEW

**Comment by kiivihal** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by glamcloud — APPROVED** [review]

**Review by glamcloud — APPROVED** [review]

**Comment by glamcloud** [comment]
cla

**Comment by glamcloud** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kiivihal** [comment]
recheckcla

**Pull request merged**
